#!/bin/bash

# Where is this script located?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
export GOPATH="$PWD"/.gopath/
export BASEDIR="$PWD"



prefix="polydawn.net/docket"
packages=()
packages+=("$prefix/crocker")
packages+=("$prefix/dex")
packages+=("$prefix/util")
packages+=("$prefix/conf")



function build {
	go build -race -o docket $prefix/main
}



function test {
	echo "${packages[@]}" | xargs go test -race
	# `go help packages` claims that "polydawn.net/docket/..." is a valid way to ask to test all packages.
	# evidentally this is a lie.
}



case "$1" in
        build)
                build
                ;;
        test)
                test
                ;;
        *)
                echo "Usage: $0 {build|test}" 1>&2;
                exit 1
                ;;
esac


